name: Display README on Release

on:
  release:
    types: [published]

jobs:
  display-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display README
        run: cat README.md
